language: python
dist: xenial
env:
- CODECOV_TOKEN="e2b3d614-88cf-46bc-ab77-188545603fa0"
services:
- docker
python:
- "3.6"
- "3.7"
install:
- pip install -r requirements.txt
- pip install codecov
script:
- coverage run project/test/run_tests.py
after_success:
- codecov