language: python
dist: xenial
services:
- docker
python:
- "3.6"
- "3.7"
install:
- pip install -r requirements.txt
- pip install codecov
script:
- coverage run project/test/run_tests.py
after_success:
- codecov